# Generated by Django 4.2 on 2023-04-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_doctype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctype',
            name='category',
        ),
    ]
