# Generated by Django 4.2 on 2023-04-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_news_options_gallery_active_teacher_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/authors/', verbose_name='Изображение'),
        ),
    ]
