# Generated by Django 4.2 on 2023-05-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='doctype',
            name='doctype_name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='doctype',
            name='doctype_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_kk',
            field=models.FileField(null=True, upload_to='main/docs/', verbose_name='Исходный файл'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_ru',
            field=models.FileField(null=True, upload_to='main/docs/', verbose_name='Исходный файл'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип документа'),
        ),
    ]
