# Generated by Django 4.2 on 2023-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfile',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
