# Generated by Django 4.2 on 2023-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_docfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfile',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создание'),
        ),
    ]
