# Generated by Django 4.2 on 2023-11-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_docfile_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='source',
        ),
        migrations.RemoveField(
            model_name='document',
            name='source_kk',
        ),
        migrations.RemoveField(
            model_name='document',
            name='source_ru',
        ),
    ]
