# Generated by Django 4.2 on 2023-11-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_document_source_remove_document_source_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docfile',
            options={'ordering': ('-date_created',), 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-date_created',), 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
